CarRentalManagment/Controllers/AdminController.cs
using CarRentalManagment.Models;
using CarRentalManagment.Models.Services;
using Microsoft.AspNetCore.Mvc;

namespace CarRentalManagment.Controllers
{
    public class AdminController : Controller
    {
        IAccountServices _services;
        public AdminController(IAccountServices services)
        {
            _services = services;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(int id, string password)
        {
            if (!(id == 0) || !(password == "1234"))
            {
                ViewBag.error = "Wrong Credentials";
                return View();
            }
            return RedirectToAction("GetAllAccounts");

        }
        public IActionResult GetAllAccounts()
        {
            var accounts=_services.GetAllAccounts();
            return View(accounts);
        }
        public IActionResult DeleteById(int id)
        {
            int result = _services.DeleteById(id);
            return RedirectToAction("GetAllAccounts");
        }
       public IActionResult GetAllCars()
        {
            return RedirectToAction("GetAllcars","Car");
        }

    }
}

CarRentalManagment/Controllers/BookOrderController.cs
using CarRentalManagment.Models;
using CarRentalManagment.Models.Services;
using Microsoft.AspNetCore.Mvc;

namespace CarRentalManagment.Controllers
{
    public class BookOrderController : Controller
    {
        IBookOrderServices _services;
        IRentOrderServices _rentServices;
        ICarServices _carServices;
        public BookOrderController(IBookOrderServices services, IRentOrderServices rentServices, ICarServices carServices)
        {
            _services = services;
            _rentServices = rentServices;
            _carServices= carServices;
        }

        public IActionResult GetAllBookOrders()
        {
            
            return View(_services.GetAllBookOrders());
        }
        public IActionResult RentBookOrder(int id)
        {
            BookOrder bo = _services.GetBookOrder(id);
            _services.RentBookOrder(bo);
            return RedirectToAction("GetAllBookOrders");
        }
        public IActionResult UnBookOrder(int id)
        {
            _services.UnBookOrder(id);
            return RedirectToAction("GetAllBookOrders");
        }
    }
}

CarRentalManagment/Controllers/RentOrderController.cs
using CarRentalManagment.Models;
using CarRentalManagment.Models.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace CarRentalManagment.Controllers
{
    public class RentOrderController : Controller
    {

        IRentOrderServices _services;
        IAccountServices _accountServices;
        ICarServices _carServices;
        public static int rentCarId;
        public static int returnCarId;
        public RentOrderController(IRentOrderServices services, IAccountServices accountServices, ICarServices carServices)
        {
            _services = services;
            _accountServices = accountServices;
            _carServices = carServices;
        }
        public IActionResult RentCar(int id)
        {
            rentCarId = id;
            Car car=_carServices.GetCarById(id);
            return View(car);
        }
        [HttpPost]
        public IActionResult RentCar(string accId, DateTime returnDate)
        {
            TimeSpan dif=DateTime.Now - returnDate;
            Car car = _carServices.GetCarById(rentCarId);
            
            if (accId==null || !(int.TryParse(accId.ToString(), out int id)) || returnDate<=DateTime.Now)
            {
                ViewBag.error = "Enter the proper information";
                return View(car);
            }else if(dif.Days > 365)
            {
                ViewBag.error = "Cant rent a car for more than a year";
                return View(car);
            }else if (_accountServices.GetAccount(id) == null)
            {
                ViewBag.error = "No account with ID: " + id;
                return View(car);
            }else if (_accountServices.GetAccount(id).activeOrder == true)
            {
                ViewBag.error = "This account already has an active order at the moment. To rent a new car customer must first close previous order";
                return View(car);
            }
            else
            {
                _services.RentCar(car,returnDate,id);
                return RedirectToAction("GetAllCars", "Admin");
            }
        }
        public IActionResult ReturnCar(int id)
        {
            returnCarId = id;
            Car car=_carServices.GetCarById(id);
            return View(car);
        }
        [HttpPost]
        public IActionResult ReturnCar()
        {
            Car car=_carServices.GetCarById(returnCarId);
            List<RentOrder> ro=_services.GetAllOrders();
            RentOrder r=new RentOrder();
            foreach(var order in ro)
            {
                if (order.isActive == true)
                {
                    if (order.carId == returnCarId)
                    {
                        r = order;
                        _services.ReturnCar(car, r);
                        return RedirectToAction("GetAllCars", "Admin");
                    }

                }           
            }

            
            return View(returnCarId);
        }
        public IActionResult GetOrderById(int id)
        {
            Account account=_accountServices.GetAccount(id);
            ViewBag.acc =account.name+" "+account.fatherName+"`s Order History.        Account Id: "+ id.ToString();
            List<RentOrder> ro = _services.GetOrderById(id);
            List<Car> cars = _carServices.GetAllCars();
            foreach (var order in ro)
            {
                foreach (var car in cars)
                {
                    if (car.carId == order.carId)
                    {
                        order.carId = Convert.ToInt32(car.licNo);
                        break;
                    }
                }
            }
            return View(ro);
        }
        public IActionResult GetAllOrders()
        {
            List<RentOrder> ro = _services.GetAllOrders();
            List<Car> cars = _carServices.GetAllCars();
            foreach(var order in ro)
            {
                foreach(var car in cars)
                {
                    if(car.carId == order.carId)
                    {
                        order.carId = Convert.ToInt32(car.licNo);
                        break;
                    }
                }
            }
            return View(ro);
        }
    }
}

CarRentalManagment/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRentalManagment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body{
            background:linear-gradient(white,lightblue)
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-5 py-4">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="AdminHome">CarRentalManagment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Admin" asp-action="GetAllAccounts"><strong>Accounts</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Admin" asp-action="GetAllCars"><strong>Cars</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="RentOrder" asp-action="GetAllOrders"><strong>Rent Orders</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="BookOrder" asp-action="GetAllBookOrders"><strong>Book Orders</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Account" asp-action="Index"><strong>Log Out</strong></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CarRentalManagment 
        </div>
    </footer>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CarRentalManagment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRentalManagment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body{
            background:linear-gradient(white,lightblue)
        }
    </style>
</head>
<body>
     <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-5 py-4">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Home">CarRentalManagment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Account" asp-action="Home"><strong>Home</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Account" asp-action="ShowRentHistory"><strong>Show Rent History</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Account" asp-action="About"><strong>About</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary float-right" asp-area="" asp-controller="Account" asp-action="Index"><strong>Log Out</strong></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CarRentalManagment - <a asp-area="" asp-controller="Account" asp-action="About">About</a>
        </div>
    </footer>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>